"""
report_generator.py
报告生成模块。
使用 Jinja2 模板渲染 Markdown 日报。
支持外部模板覆盖，内置默认模板兜底。
"""
import logging
import shutil
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from jinja2 import Template

from src.engine.matcher import Recommendation
from src.storage.vector_store import VectorStore

logger = logging.getLogger("future-agent.generators")

DEFAULT_TEMPLATE = """# 📚 Future-Agent Daily Report —— {{ date }}

## 你的知识状态快照
- 当前笔记库：{{ stats.notes_count }} 篇技术笔记
- 今日 arXiv 监控：{{ stats.papers_count }} 篇新论文
- 推荐策略：{{ strategy }}

---

## 🔥 今日推荐（Top {{ recommendations|length }}）

{% for rec in recommendations %}
### {{ loop.index }}. {{ rec.title }} —— {% if rec.diversity_bucket == 'strong' %}强相关 ⭐{% elif rec.diversity_bucket == 'boundary' %}边界拓展 🌱{% else %}跨界探索 🚀{% endif %}
**作者**：{{ rec.authors }}  
**arXiv ID**：{{ rec.arxiv_id }}  
**分类**：{{ rec.categories | join(', ') }}  
**发布日期**：{{ rec.published }}  
**PDF**：{{ rec.pdf_url }}

**关联笔记**：《{{ rec.matched_note }}》  
**相似度**：{{ "%.3f"|format(rec.similarity) }}

**推荐理由**：  
{{ rec.explanation }}

**摘要预览**：  
> {{ rec.abstract[:300] }}{% if rec.abstract|length > 300 %}...{% endif %}

---
{% endfor %}

*Generated by Future-Agent v1.0 at {{ now }}*
"""

EMPTY_TEMPLATE = """# 📚 Future-Agent Daily Report —— {{ date }}

## 今日状态
- 监控论文池：arXiv {{ arxiv_cats|join(' / ') }} 最近 {{ days }} 天共 {{ stats.papers_count }} 篇
- 笔记库匹配：当前笔记库 {{ stats.notes_count }} 篇，未找到高相关论文

## 🌵 今日无高相关论文

这很正常。arXiv 每天数百篇论文中，与你当前知识状态强相关的可能只有 0-2 篇。

**建议**：
1. 扩大监控范围：`future-agent fetch --days 7 --max-results 200`
2. 增加监控分类：在 config.yaml 中加入 `cs.DB`, `cs.CV`
3. 回顾已有笔记：用 `future-agent status` 查看当前知识库覆盖度

*宁无推荐，不错推荐！*
"""


class ReportGenerator:
    """
    Markdown 日报生成器。
    """

    def __init__(self, config: Optional[dict] = None) -> None:
        self.config = config or {}
        template_path = self.config.get(
            "report.template", "./templates/daily_report.md.j2"
        )

        tp = Path(template_path)
        if tp.exists() and tp.stat().st_size > 0:
            self.template = Template(tp.read_text(encoding="utf-8"))
            logger.info(f"📋 加载外部模板: {tp}")
        else:
            self.template = Template(DEFAULT_TEMPLATE)
            logger.info("📋 使用内置默认模板")

    def generate(
        self,
        recommendations: List[Recommendation],
        output_dir: Path,
        date_str: str,
        strategy: str = "boundary_mix",
    ) -> Path:
        """
        渲染并保存日报。

        Returns:
            生成的报告文件路径
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        report_path = output_dir / f"{date_str}_daily_report.md"

        # 获取统计信息
        store = VectorStore(self.config)
        stats = store.stats()

        # 根据是否有推荐选择模板
        if not recommendations:
            template = Template(EMPTY_TEMPLATE)
        else:
            template = self.template

        arxiv_cats = self.config.get("arxiv.categories", ["cs.CL", "cs.LG"])
        days = self.config.get("arxiv.date_range_days", 7)

        context = {
            "date": date_str,
            "now": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "strategy": strategy,
            "recommendations": recommendations,
            "stats": stats,
            "arxiv_cats": arxiv_cats,
            "days": days,
        }

        markdown = template.render(context)
        report_path.write_text(markdown, encoding="utf-8")

        if recommendations:
            logger.info(f"📄 报告已保存: {report_path}")
        else:
            logger.info(f"📄 无推荐日报已保存: {report_path}")
        return report_path

    @staticmethod
    def copy_to_inbox(report_path: Path, inbox_path: Path) -> None:
        """将报告复制到 Obsidian Inbox。"""
        inbox_path.mkdir(parents=True, exist_ok=True)
        dest = inbox_path / report_path.name
        shutil.copy2(report_path, dest)
        logger.info(f"📥 已复制到 Inbox: {dest}")